### ISSUE TITLE
Validation Problem

### ISSUE THREAD

**Issue by vicabelotelova** [kekeh/ngx-mydatepicker#105] opened 2017-11-03 08:08 UTC
I have same issue like this https://github.com/kekeh/ngx-mydatepicker/issues/93
i use "ngx-mydatepicker": "^2.1.0"

i use validators.pattern in my application

**Comment by kekeh** [comment] 2017-11-05 09:05
In calendar can you see disabled dates colored as red? The typing disabled date to input box should set valid flag of the **inputFieldChanged** callback to **false**. It is basic functionality.

I am not able to reproduce this issue.

**Comment by kekeh** [comment] 2017-11-05 09:20
You can fork this plunker: http://plnkr.co/edit/C36Y9I?p=info

and create configuration to forked plunker which causes this issue.

**Comment by kekeh** [comment] 2017-12-26 12:53
Closing this issue because no answer.

**Closed by kekeh** 2017-12-26 12:53 UTC
