### ISSUE TITLE
Datepicker closes after year or month changes

### ISSUE THREAD

**Issue by VladislavBI** [kekeh/ngx-mydatepicker#118] opened 2017-12-26 18:15 UTC
I have used 2.1.3 version before and I have no problems neither with year nor with month change on datapicker . After I have updated my package and have installed 2.4.0 version this appends. Please contact me if you will need any additional details

**Comment by kekeh** [comment] 2017-12-27 05:54
Hi @VladislavBI 

Can you provide step by step instructions on how to reproduce this issue.

**Comment by kekeh** [comment] 2018-01-20 09:11
Closing because no answer.

**Closed by kekeh** 2018-01-20 09:11 UTC
